# handlers file for rhel8_cis

- name: sysctl flush ipv4 route table
  become: yes
  sysctl:
    name: net.ipv4.route.flush
    value: 1
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: sysctl flush ipv6 route table
  become: yes
  sysctl:
    name: net.ipv6.route.flush
    value: 1
    sysctl_set: yes
  when: ansible_virtualization_type != "docker"

- name: systemd restart tmp.mount
  become: yes
  ignore_errors: true
  systemd:
    name: tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: systemd restart var-tmp.mount
  become: yes
  ignore_errors: true
  systemd:
    name: var-tmp.mount
    daemon_reload: yes
    enabled: yes
    masked: no
    state: reloaded

- name: generate new grub config
  become: yes
  command: grub2-mkconfig -o "{{ grub_cfg.stat.lnk_source if grub_cfg.stat.islnk else
    grub_cfg.stat.path }}"

- name: restart firewalld
  become: yes
  service:
    name: firewalld
    state: restarted

- name: restart xinetd
  become: yes
  service:
    name: xinetd
    state: restarted

- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted

- name: reload dconf
  become: yes
  command: dconf update

- name: restart auditd
  command: /sbin/service auditd restart
  changed_when: no
  check_mode: no
  failed_when: no
  args:
    warn: no
  when:
    - ansible_virtualization_type != "docker"
  tags:
    - skip_ansible_lint

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
